### ISSUE TITLE
Syntax error on pip install

### ISSUE THREAD

**Issue by magee256** [ionelmc/python-lazy-object-proxy#35]
When attempting to pip install version 1.4.2+ of lazy-object-proxy I get the error:

```
  ERROR: Command errored out with exit status 1:
   command: /Users/magee1/anaconda3/bin/python /Users/magee1/anaconda3/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/fn/hmxmmk5n4bxcpwxhzqdf_53w0000gn/T/pip-build-env-6iww4w57/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=30.3.0' wheel 'setuptools_scm>=3.3.1'
       cwd: None
  Complete output (41 lines):
  Traceback (most recent call last):
    File "/Users/magee1/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/Users/magee1/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/Users/magee1/anaconda3/lib/python3.6/site-packages/pip/__main__.py", line 19, in <module>
      sys.exit(_main())
    File "/Users/magee1/anaconda3/lib/python3.6/site-packages/pip/_internal/cli/main.py", line 73, in main
      command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
    File "/Users/magee1/anaconda3/lib/python3.6/site-packages/pip/_internal/commands/__init__.py", line 96, in create_command
      module = importlib.import_module(module_path)
    File "/Users/magee1/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 994, in _gcd_import
    File "<frozen importlib._bootstrap>", line 971, in _find_and_load
    File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 678, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/Users/magee1/anaconda3/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 24, in <module>
      from pip._internal.cli.req_command import RequirementCommand
    File "/Users/magee1/anaconda3/lib/python3.6/site-packages/pip/_internal/cli/req_command.py", line 21, in <module>
      from pip._internal.req.constructors import (
    File "/Users/magee1/anaconda3/lib/python3.6/site-packages/pip/_internal/req/__init__.py", line 11, in <module>
      from .req_file import parse_requirements
    File "/Users/magee1/anaconda3/lib/python3.6/site-packages/pip/_internal/req/req_file.py", line 25, in <module>
      from pip._internal.req.constructors import (
    File "/Users/magee1/anaconda3/lib/python3.6/site-packages/pip/_internal/req/constructors.py", line 28, in <module>
      from pip._internal.req.req_install import InstallRequirement
    File "/Users/magee1/anaconda3/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 30, in <module>
      from pip._internal.operations.install.wheel import install_wheel
    File "/Users/user/anaconda3/lib/python3.6/site-packages/pip/_internal/operations/install/wheel.py", line 10, in <module>
      import compileall
    File "/Users/magee1/anaconda3/lib/python3.6/compileall.py", line 20, in <module>
      from concurrent.futures import ProcessPoolExecutor
    File "/Users/magee1/anaconda3/lib/python3.6/site-packages/concurrent/futures/__init__.py", line 8, in <module>
      from concurrent.futures._base import (FIRST_COMPLETED,
    File "/Users/magee1/anaconda3/lib/python3.6/site-packages/concurrent/futures/_base.py", line 381
      raise exception_type, self._exception, self._traceback
                          ^
  SyntaxError: invalid syntax
```

Version 1.4.1 successfully installs. 

Some version info:
pip: 20.0.2
python: Python 3.6.4 :: Anaconda, Inc.

**Comment by ionelmc** [comment]
Are you sure you're testing this in a clean environment? lazy-object-proxy only has setuptools-scm as a setup_requires requirement, and install_requires is empty. Something else pulls in that broken concurrent.futures package.
