### ISSUE TITLE
Low Pri: pip install on 3.9 fails

### ISSUE THREAD

**Issue by cooperlees** [ionelmc/python-lazy-object-proxy#36]
pip fails to install - But seems it might be a bug with something else:
```
[?25hCollecting lazy-object-proxy==1.4.*
  Downloading lazy-object-proxy-1.4.3.tar.gz (34 kB)
  Installing build dependencies ... [?25l- \ | / done
[?25h  Getting requirements to build wheel ... [?25ldone
[?25h    Preparing wheel metadata ... [?25l- error
[31m    ERROR: Command errored out with exit status 1:
     command: /home/travis/virtualenv/python3.9-dev/bin/python /home/travis/virtualenv/python3.9-dev/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpsndzhvc0
         cwd: /tmp/pip-install-f3rexa72/lazy-object-proxy
    Complete output (42 lines):
    /home/travis/virtualenv/python3.9-dev/bin/python: No module named pip
    Traceback (most recent call last):
      File "/home/travis/virtualenv/python3.9-dev/lib/python3.9/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/opt/python/3.9-dev/lib/python3.9/subprocess.py", line 372, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/home/travis/virtualenv/python3.9-dev/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpie9x_bnr', '--quiet', 'setuptools_scm>=3.3.1']' returned non-zero exit status 1.
```

Full ci job log with failure: https://pastebin.com/Sb2SufJh

I didn't dig in deep - So close if you think this is not related to lazy-object-proxy or you can't repro.

**Comment by ionelmc** [comment]
So I take it only happens on py3.9?

**Comment by cooperlees** [comment]
Yes. That's why I said that and linked to a log from a failing 3.9 CI job.

**Comment by ionelmc** [comment]
Does this still reproduce?
