### ISSUE TITLE
pip install on 3.8.2 fails

### ISSUE THREAD

**Issue by QYQSDTC** [ionelmc/python-lazy-object-proxy#40]
When I was trying to install, I got this error, but when I switch to 3.7.7, it was installed successfully. My system is macOS 10.15.5.
```
---------------------------------------------
pip install -U lazy-object-proxy
Collecting lazy-object-proxy
  Using cached lazy-object-proxy-1.5.0.tar.gz (35 kB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/qianyiqian/.pyenv/versions/3.8.2/bin/python3.8 /Users/qianyiqian/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/d7/7bg07yps3_15nmjgbvtmjv5m0000gn/T/pip-build-env-aikqnbxi/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=30.3.0' wheel 'setuptools_scm>=3.3.1'
       cwd: None
  Complete output (44 lines):
  Traceback (most recent call last):
    File "/Users/qianyiqian/.pyenv/versions/3.8.2/lib/python3.8/runpy.py", line 193, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/Users/qianyiqian/.pyenv/versions/3.8.2/lib/python3.8/runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "/Users/qianyiqian/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pip/__main__.py", line 26, in <module>
      sys.exit(_main())
    File "/Users/qianyiqian/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 73, in main
      command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
    File "/Users/qianyiqian/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pip/_internal/commands/__init__.py", line 104, in create_command
      module = importlib.import_module(module_path)
    File "/Users/qianyiqian/.pyenv/versions/3.8.2/lib/python3.8/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 783, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/Users/qianyiqian/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 24, in <module>
      from pip._internal.cli.req_command import RequirementCommand, with_cleanup
    File "/Users/qianyiqian/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 16, in <module>
      from pip._internal.index.package_finder import PackageFinder
    File "/Users/qianyiqian/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pip/_internal/index/package_finder.py", line 21, in <module>
      from pip._internal.index.collector import parse_links
    File "/Users/qianyiqian/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pip/_internal/index/collector.py", line 14, in <module>
      from pip._vendor import html5lib, requests
    File "/Users/qianyiqian/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pip/_vendor/requests/__init__.py", line 114, in <module>
      from . import utils
    File "/Users/qianyiqian/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pip/_vendor/requests/utils.py", line 25, in <module>
      from . import certs
    File "/Users/qianyiqian/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pip/_vendor/requests/certs.py", line 15, in <module>
      from pip._vendor.certifi import where
    File "/Users/qianyiqian/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pip/_vendor/certifi/__init__.py", line 1, in <module>
      from .core import contents, where
    File "/Users/qianyiqian/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pip/_vendor/certifi/core.py", line 12, in <module>
      from importlib.resources import read_text
    File "/Users/qianyiqian/.pyenv/versions/3.8.2/lib/python3.8/importlib/resources.py", line 11, in <module>
      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401
    File "/Users/qianyiqian/.pyenv/versions/3.8.2/lib/python3.8/site-packages/typing.py", line 1357, in <module>
      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
    File "/Users/qianyiqian/.pyenv/versions/3.8.2/lib/python3.8/site-packages/typing.py", line 1005, in __new__
      self._abc_registry = extra._abc_registry
  AttributeError: type object 'Callable' has no attribute '_abc_registry'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/qianyiqian/.pyenv/versions/3.8.2/bin/python3.8 /Users/qianyiqian/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/d7/7bg07yps3_15nmjgbvtmjv5m0000gn/T/pip-build-env-aikqnbxi/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=30.3.0' wheel 'setuptools_scm>=3.3.1' Check the logs for full command output.
```

**Comment by ionelmc** [comment]
The error comes from the `typing` module, please see https://pypi.org/project/typing/ for how to report the bug.

lazy-object-proxy doesn't require `typing`. Your problem will likely reproduce with any pip command.
