### ISSUE TITLE
Python 2.7 install fails with 1.7.0

### ISSUE THREAD

**Issue by ghost** [ionelmc/python-lazy-object-proxy#63]
### ENVIRONMENT

Python 2.7

### ISSUE:

`
Collecting lazy-object-proxy
  Downloading lazy-object-proxy-1.7.0.tar.gz (42 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'error'
[91m    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python /usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp10FvRf
         cwd: /tmp/pip-install-56yjxy/lazy-object-proxy
    Complete output (46 lines):
    running dist_info
    creating /tmp/pip-modern-metadata-e9SZ8M/lazy_object_proxy.egg-info
    writing /tmp/pip-modern-metadata-e9SZ8M/lazy_object_proxy.egg-info/PKG-INFO
    writing top-level names to /tmp/pip-modern-metadata-e9SZ8M/lazy_object_proxy.egg-info/top_level.txt
    writing dependency_links to /tmp/pip-modern-metadata-e9SZ8M/lazy_object_proxy.egg-info/dependency_links.txt
    writing manifest file '/tmp/pip-modern-metadata-e9SZ8M/lazy_object_proxy.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-zxqD3G/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 156, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/tmp/pip-build-env-zxqD3G/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 243, in run_setup
        self).run_setup(setup_script=setup_script)
      File "/tmp/pip-build-env-zxqD3G/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 146, in <module>
        distclass=BinaryDistribution,
      File "/tmp/pip-build-env-zxqD3G/overlay/lib/python2.7/site-packages/setuptools/__init__.py", line 162, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-env-zxqD3G/overlay/lib/python2.7/site-packages/setuptools/command/dist_info.py", line 31, in run
        egg_info.run()
      File "/tmp/pip-build-env-zxqD3G/overlay/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 296, in run
        self.find_sources()
      File "/tmp/pip-build-env-zxqD3G/overlay/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 303, in find_sources
        mm.run()
      File "/tmp/pip-build-env-zxqD3G/overlay/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 534, in run
        self.add_defaults()
      File "/tmp/pip-build-env-zxqD3G/overlay/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 570, in add_defaults
        sdist.add_defaults(self)
      File "/tmp/pip-build-env-zxqD3G/overlay/lib/python2.7/site-packages/setuptools/command/py36compat.py", line 36, in add_defaults
        self._add_defaults_ext()
      File "/tmp/pip-build-env-zxqD3G/overlay/lib/python2.7/site-packages/setuptools/command/py36compat.py", line 118, in _add_defaults_ext
        if self.distribution.has_ext_modules():
      File "setup.py", line 70, in has_ext_modules
        return super().has_ext_modules() or 'SETUP_PY_ALLOW_PURE' not in os.environ
    TypeError: super() takes at least 1 argument (0 given)
    ----------------------------------------
[0m[91mERROR: Command errored out with exit status 1: /usr/bin/python /usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp10FvRf Check the logs for full command output.
`

### REASON:

`python_requires='>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, !=3.5.*',`

### HOW TO FIX:

Remove **>=2.7**

**Comment by ionelmc** [comment]
OOoof. 1.7.0 should be yanked but it would appear your installer still installs it. Did you have `lazy-object-proxy==1.7.0` in your requirements?

Anyway, 1.7+ is py3 only.

**Comment by mmalta-daily** [comment]
It happens because of Pylint having a dependency to Astroid which has a lazy dependency to this package :(

https://github.com/PyCQA/astroid/blob/astroid-1.6.6/astroid/__pkginfo__.py#L23

**Comment by ionelmc** [comment]
Can't you just pin lazy-object-proxy to 1.6.0? There won't be future
releases for 2.7 anyway...

**Comment by sshishov** [comment]
@mmalta-daily after yanking the package, it should not happen... let me validate

**Comment by sbidoul** [comment]
yank support has been added in pip 19.2, so users having an older pip might still get 1.7.0 on python 2.7. Upgrading pip or pinning "<1.7.0" is the solution.
