### ISSUE TITLE
Is Python 3.11 supported? Getting an error on pip install 

### ISSUE THREAD

**Issue by harshil21** [ionelmc/python-lazy-object-proxy#68]
I wanted to install `pylint`, but installing an error gave an error since it couldn't install this lib.

### Command used:

`python3.11 -m pip install lazy-object-proxy`

### Error log:

<details>
<summary> Log </summary>

```
$ python3.11 -m pip install lazy-object-proxy
Defaulting to user installation because normal site-packages is not writeable
Collecting lazy-object-proxy
  Using cached lazy-object-proxy-1.7.1.tar.gz (41 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: lazy-object-proxy
  Building wheel for lazy-object-proxy (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for lazy-object-proxy (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [93 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.11
      creating build/lib.linux-x86_64-3.11/lazy_object_proxy
      copying src/lazy_object_proxy/utils_py3.py -> build/lib.linux-x86_64-3.11/lazy_object_proxy
      copying src/lazy_object_proxy/utils.py -> build/lib.linux-x86_64-3.11/lazy_object_proxy
      copying src/lazy_object_proxy/_version.py -> build/lib.linux-x86_64-3.11/lazy_object_proxy
      copying src/lazy_object_proxy/slots.py -> build/lib.linux-x86_64-3.11/lazy_object_proxy
      copying src/lazy_object_proxy/__init__.py -> build/lib.linux-x86_64-3.11/lazy_object_proxy
      copying src/lazy_object_proxy/compat.py -> build/lib.linux-x86_64-3.11/lazy_object_proxy
      copying src/lazy_object_proxy/simple.py -> build/lib.linux-x86_64-3.11/lazy_object_proxy
      running build_ext
      creating build/temp.linux-x86_64-3.11
      creating build/temp.linux-x86_64-3.11/src
      creating build/temp.linux-x86_64-3.11/src/lazy_object_proxy
      x86_64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -Isrc/lazy_object_proxy -I/usr/include/python3.11 -c src/lazy_object_proxy/cext.c -o build/temp.linux-x86_64-3.11/src/lazy_object_proxy/cext.o
      src/lazy_object_proxy/cext.c:3:10: fatal error: Python.h: No such file or directory
          3 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      ********************************************************************************
      WARNING:
      
          An optional code optimization (C extension) could not be compiled.
      
          Optimizations for this package will not be available!
      
      CAUSE:
      
          CompileError(DistutilsExecError("command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1"))
      ********************************************************************************
      running install
      running install_lib
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 230, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
          self.run_setup()
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 268, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 73, in <module>
          setup(
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 335, in run
          self.run_command('install')
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/command/install.py", line 622, in run
          self.run_command(cmd_name)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 985, in run_command
          cmd_obj.ensure_finalized()
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 107, in ensure_finalized
          self.finalize_options()
        File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 17, in finalize_options
          self.set_undefined_options('install',('install_layout','install_layout'))
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 290, in set_undefined_options
          setattr(self, dst_option, getattr(src_cmd_obj, src_option))
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 103, in __getattr__
          raise AttributeError(attr)
      AttributeError: install_layout. Did you mean: 'install_platlib'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lazy-object-proxy
Failed to build lazy-object-proxy
ERROR: Could not build wheels for lazy-object-proxy, which is required to install pyproject.toml-based projects
```

</details>

### Details

Python version: 3.11b5
OS: Ubuntu 22.04 on WSL2

**Comment by ionelmc** [comment]
You appear to be missing the devel headers.

**Comment by harshil21** [comment]
Thanks, solved the first part of missing header by running `sudo apt install python3.11-dev`, but the second part of the error remains. From https://github.com/pypa/pip/issues/10857, I guess this is not related with this package, so closing.
