### ISSUE TITLE
Python 3.11 Support ? An Error on install

### ISSUE THREAD

**Issue by kashifkhan** [ionelmc/python-lazy-object-proxy#71]
I am trying to install this library on Ubuntu 20.04 using Azure pipelines. I'm using py311rc2. Are there any other dependencies that are needed ?

**Error Log**
2022-09-23T20:43:46.9989896Z Collecting lazy-object-proxy>=1.4.0
2022-09-23T20:43:47.0119091Z   Downloading lazy-object-proxy-1.7.1.tar.gz (41 kB)
2022-09-23T20:43:47.0173957Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.0/42.0 kB 11.1 MB/s eta 0:00:00
2022-09-23T20:43:47.0368283Z   Installing build dependencies: started
2022-09-23T20:43:49.4723188Z   Installing build dependencies: finished with status 'done'
2022-09-23T20:43:49.4816387Z   Getting requirements to build wheel: started
2022-09-23T20:43:49.7517171Z   Getting requirements to build wheel: finished with status 'done'
2022-09-23T20:43:49.7619334Z   Preparing metadata (pyproject.toml): started
2022-09-23T20:43:50.2802387Z   Preparing metadata (pyproject.toml): finished with status 'error'
2022-09-23T20:43:50.2895982Z   error: subprocess-exited-with-error
2022-09-23T20:43:50.2898417Z   
2022-09-23T20:43:50.2916463Z   × Preparing metadata (pyproject.toml) did not run successfully.
2022-09-23T20:43:50.2923431Z   │ exit code: 1
2022-09-23T20:43:50.2925564Z   ╰─> [74 lines of output]
2022-09-23T20:43:50.2927302Z       running dist_info
2022-09-23T20:43:50.2930582Z       creating /tmp/pip-modern-metadata-aa94fjhm/lazy_object_proxy.egg-info
2022-09-23T20:43:50.2933404Z       writing /tmp/pip-modern-metadata-aa94fjhm/lazy_object_proxy.egg-info/PKG-INFO
2022-09-23T20:43:50.2936096Z       writing dependency_links to /tmp/pip-modern-metadata-aa94fjhm/lazy_object_proxy.egg-info/dependency_links.txt
2022-09-23T20:43:50.2938800Z       writing top-level names to /tmp/pip-modern-metadata-aa94fjhm/lazy_object_proxy.egg-info/top_level.txt
2022-09-23T20:43:50.2942119Z       writing manifest file '/tmp/pip-modern-metadata-aa94fjhm/lazy_object_proxy.egg-info/SOURCES.txt'
2022-09-23T20:43:50.2945116Z       listing git files failed - pretending there aren't any
2022-09-23T20:43:50.2947594Z       reading manifest file '/tmp/pip-modern-metadata-aa94fjhm/lazy_object_proxy.egg-info/SOURCES.txt'
2022-09-23T20:43:50.2951900Z       adding license file 'LICENSE'
2022-09-23T20:43:50.2954350Z       adding license file 'AUTHORS.rst'
2022-09-23T20:43:50.2956778Z       writing manifest file '/tmp/pip-modern-metadata-aa94fjhm/lazy_object_proxy.egg-info/SOURCES.txt'
2022-09-23T20:43:50.2960065Z       creating '/tmp/pip-modern-metadata-aa94fjhm/lazy_object_proxy-1.7.1.dist-info'
2022-09-23T20:43:50.2963066Z       Traceback (most recent call last):
2022-09-23T20:43:50.2966053Z         File "/home/vsts/.local/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
2022-09-23T20:43:50.2968307Z           main()
2022-09-23T20:43:50.2970651Z         File "/home/vsts/.local/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
2022-09-23T20:43:50.2973122Z           json_out['return_val'] = hook(**hook_input['kwargs'])
2022-09-23T20:43:50.2975021Z                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2022-09-23T20:43:50.2978183Z         File "/home/vsts/.local/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
2022-09-23T20:43:50.2981123Z           return hook(metadata_directory, config_settings)
2022-09-23T20:43:50.2983206Z                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2022-09-23T20:43:50.2986055Z         File "/tmp/pip-build-env-cm625ym7/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 377, in prepare_metadata_for_build_wheel
2022-09-23T20:43:50.2989210Z           self.run_setup()
2022-09-23T20:43:50.2992200Z         File "/tmp/pip-build-env-cm625ym7/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 483, in run_setup
2022-09-23T20:43:50.2994534Z           self).run_setup(setup_script=setup_script)
2022-09-23T20:43:50.2996707Z                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2022-09-23T20:43:50.2999229Z         File "/tmp/pip-build-env-cm625ym7/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 335, in run_setup
2022-09-23T20:43:50.3001375Z           exec(code, locals())
2022-09-23T20:43:50.3003094Z         File "<string>", line 73, in <module>
2022-09-23T20:43:50.3008648Z         File "/tmp/pip-build-env-cm625ym7/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 87, in setup
2022-09-23T20:43:50.3011438Z           return distutils.core.setup(**attrs)
2022-09-23T20:43:50.3013595Z                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2022-09-23T20:43:50.3016500Z         File "/tmp/pip-build-env-cm625ym7/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
2022-09-23T20:43:50.3019072Z           return run_commands(dist)
2022-09-23T20:43:50.3021153Z                  ^^^^^^^^^^^^^^^^^^
2022-09-23T20:43:50.3024257Z         File "/tmp/pip-build-env-cm625ym7/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
2022-09-23T20:43:50.3026965Z           dist.run_commands()
2022-09-23T20:43:50.3030180Z         File "/tmp/pip-build-env-cm625ym7/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
2022-09-23T20:43:50.3032648Z           self.run_command(cmd)
2022-09-23T20:43:50.3035515Z         File "/tmp/pip-build-env-cm625ym7/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
2022-09-23T20:43:50.3038530Z           super().run_command(command)
2022-09-23T20:43:50.3041466Z         File "/tmp/pip-build-env-cm625ym7/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
2022-09-23T20:43:50.3043956Z           cmd_obj.run()
2022-09-23T20:43:50.3046627Z         File "/tmp/pip-build-env-cm625ym7/overlay/lib/python3.11/site-packages/setuptools/command/dist_info.py", line 101, in run
2022-09-23T20:43:50.3049680Z           bdist_wheel = self.get_finalized_command('bdist_wheel')
2022-09-23T20:43:50.3051677Z                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2022-09-23T20:43:50.3054192Z         File "/tmp/pip-build-env-cm625ym7/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 305, in get_finalized_command
2022-09-23T20:43:50.3056532Z           cmd_obj = self.distribution.get_command_obj(command, create)
2022-09-23T20:43:50.3058656Z                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2022-09-23T20:43:50.3063621Z         File "/tmp/pip-build-env-cm625ym7/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 864, in get_command_obj
2022-09-23T20:43:50.3066635Z           klass = self.get_command_class(command)
2022-09-23T20:43:50.3068953Z                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2022-09-23T20:43:50.3071563Z         File "/tmp/pip-build-env-cm625ym7/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 954, in get_command_class
2022-09-23T20:43:50.3073777Z           self.cmdclass[command] = cmdclass = ep.load()
2022-09-23T20:43:50.3075578Z                                               ^^^^^^^^^
2022-09-23T20:43:50.3078008Z         File "/opt/hostedtoolcache/Python/3.11.0-rc.2/x64/lib/python3.11/importlib/metadata/__init__.py", line 198, in load
2022-09-23T20:43:50.3080443Z           module = import_module(match.group('module'))
2022-09-23T20:43:50.3082295Z                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2022-09-23T20:43:50.3084710Z         File "/opt/hostedtoolcache/Python/3.11.0-rc.2/x64/lib/python3.11/importlib/__init__.py", line 126, in import_module
2022-09-23T20:43:50.3086987Z           return _bootstrap._gcd_import(name[level:], package, level)
2022-09-23T20:43:50.3088996Z                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2022-09-23T20:43:50.3090893Z         File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
2022-09-23T20:43:50.3092888Z         File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
2022-09-23T20:43:50.3095319Z         File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
2022-09-23T20:43:50.3098075Z         File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
2022-09-23T20:43:50.3100633Z         File "<frozen importlib._bootstrap_external>", line 940, in exec_module
2022-09-23T20:43:50.3103184Z         File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2022-09-23T20:43:50.3105873Z         File "/tmp/pip-build-env-cm625ym7/overlay/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 26, in <module>
2022-09-23T20:43:50.3108157Z           from .macosx_libfile import calculate_macosx_platform_tag
2022-09-23T20:43:50.3111144Z         File "/tmp/pip-build-env-cm625ym7/overlay/lib/python3.11/site-packages/wheel/macosx_libfile.py", line 41, in <module>
2022-09-23T20:43:50.3113240Z           import ctypes
2022-09-23T20:43:50.3116189Z         File "/opt/hostedtoolcache/Python/3.11.0-rc.2/x64/lib/python3.11/ctypes/__init__.py", line 8, in <module>
2022-09-23T20:43:50.3118510Z           from _ctypes import Union, Structure, Array
2022-09-23T20:43:50.3120924Z       ImportError: libffi.so.6: cannot open shared object file: No such file or directory
2022-09-23T20:43:50.3122815Z       [end of output]

**Comment by kashifkhan** [comment]
Solved it by using the instructions provided [here](https://stackoverflow.com/questions/61875869/ubuntu-20-04-upgrade-python-missing-libffi-so-6).
